version = 1

exclude_patterns = ["src/components/form/FormSubmissionHandler.js"]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]

[[transformers]]
name = "prettier"
enabled = true
